"""create leads and activities

Epic 1, the first Lego block: the Lead table and the append-only activity
history behind it. Shapes are frozen in docs/delivery/epic-1-lead-contract.md.

Autogenerated from the models and reviewed by hand; `alembic check` should
report no drift from app/models while this is the head revision.

Revision ID: 0001
Revises:
Create Date: 2026-10-09 12:35:59.871525
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "leads",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("business_name", sa.String(length=255), nullable=False),
        sa.Column("sector", sa.String(length=255), nullable=True),
        sa.Column("area", sa.String(length=255), nullable=True),
        # E.164, and the de-duplication key. Postgres allows many NULLs here.
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("whatsapp_capable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("website_status", sa.Text(), nullable=True),
        sa.Column("has_website", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        # A varchar plus a check constraint, not a native enum: adding a status
        # later is then an ordinary migration.
        sa.Column(
            "status",
            sa.Enum(
                "new",
                "contacted",
                "replied",
                "qualified",
                "handed_off",
                "proposal",
                "won",
                "lost",
                "no_response",
                "not_interested",
                "opted_out",
                name="lead_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            server_default="new",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("business_name <> ''", name=op.f("ck_leads_business_name_not_blank")),
        sa.CheckConstraint("source <> ''", name=op.f("ck_leads_source_not_blank")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leads")),
        sa.UniqueConstraint("phone", name=op.f("uq_leads_phone")),
    )
    op.create_table(
        "activities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("actor", sa.String(length=64), server_default="system", nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
            name=op.f("fk_activities_lead_id_leads"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activities")),
    )
    op.create_index(
        "ix_activities_lead_id_created_at",
        "activities",
        ["lead_id", "created_at"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index("ix_activities_lead_id_created_at", table_name="activities")
    op.drop_table("activities")
    op.drop_table("leads")
